Repository ComputationalPsychiatry/pyhgf, pull requests merged in 2023-09, with the labels that each got.

#89 CPC tutorial and documentation
  docs/source/notebooks/1.1-Binary_HGF.ipynb
  docs/source/notebooks/1.1-Binary_HGF.md
  docs/source/notebooks/1.2-Categorical_HGF.ipynb
  docs/source/notebooks/Exercise_1_Using_the_HGF.ipynb
  docs/source/notebooks/Exercise_1_Using_the_HGF.md
  pyhgf/model.py
  pyhgf/networks.py
  pyhgf/plots.py
Labels: documentation

#105 rewrite and simplify the update functions
  docs/source/api.rst
  src/pyhgf/updates/binary.py
  src/pyhgf/updates/continuous.py
  src/pyhgf/updates/prediction/binary.py
  src/pyhgf/updates/prediction/continuous.py
  src/pyhgf/updates/prediction_error/binary.py
  src/pyhgf/updates/prediction_error/continuous.py
  tests/test_distribution.py
  tests/test_networks.py
Labels: update functions

#102 add figure and notebook for the method paper
  README.md
  docs/source/images/graph_networks.svg
Labels: documentation

#106 simplify update functions
  docs/source/api.rst
  src/pyhgf/updates/binary.py
  src/pyhgf/updates/continuous.py
  src/pyhgf/updates/prediction/binary.py
  src/pyhgf/updates/prediction/continuous.py
  src/pyhgf/updates/prediction_error/continuous.py
Labels: update functions

#109 prediction update only apply to the target node
  docs/source/api.rst
  src/pyhgf/networks.py
  src/pyhgf/updates/binary.py
  src/pyhgf/updates/continuous.py
  src/pyhgf/updates/prediction/binary.py
  tests/test_binary.py
  tests/test_continuous.py
Labels: update functions, performances

#110 Correction on docs in math.py
  src/pyhgf/math.py
Labels: documentation

#111 small fixes in the documentation
  docs/source/_static/style.css
  docs/source/conf.py
  docs/source/notebooks/Exercise_1_Using_the_HGF.ipynb
  docs/source/notebooks/Exercise_1_Using_the_HGF.md
Labels: documentation
