Repository ComputationalPsychiatry/pyhgf, pull requests merged in 2024-12, with the labels that each got.

#258 update pyo3 to 0.23.3
  .github/workflows/ci.yml
  Cargo.lock
  Cargo.toml
  src/model.rs
Labels: rust

#260 fix pre-commit paths and Rust CI
  .github/workflows/ci.yml
  .pre-commit-config.yaml
  pyhgf/model/add_nodes.py
  pyhgf/model/network.py
Labels: rust

#261 refactor continuous posterior updates module
  pyhgf/updates/posterior/continuous.py
  pyhgf/updates/posterior/continuous/__init__.py
  pyhgf/updates/posterior/continuous/continuous_node_posterior_update.py
  pyhgf/updates/posterior/continuous/continuous_node_posterior_update_ehgf.py
  pyhgf/updates/posterior/continuous/posterior_update_mean_continuous_node.py
  pyhgf/updates/posterior/continuous/posterior_update_precision_continuous_node.py
  tests/test_updates/posterior/continuous.py
Labels: update functions

#263 Split posterior precision update into two branches
  docs/source/api.rst
  pyhgf/updates/posterior/continuous/__init__.py
  pyhgf/updates/posterior/continuous/posterior_update_precision_continuous_node.py
  tests/test_updates/posterior/continuous.py
Labels: update functions

#265 Update README.md
  README.md
Labels: documentation

#267 add remove_node function
  docs/source/api.rst
  pyhgf/utils/__init__.py
  pyhgf/utils/remove_node.py
  tests/test_utils.py
Labels: networks

#268 Add add_parent function
  docs/source/api.rst
  pyhgf/utils/__init__.py
  pyhgf/utils/add_parent.py
  tests/test_utils.py
Labels: networks
