Repository ComputationalPsychiatry/pyhgf, pull requests merged in 2025-04, with the labels that each got.

#287 add an action component to the belief propagation step
  docs/source/learn.md
  docs/source/notebooks/0.2-Creating_networks.ipynb
  docs/source/notebooks/0.4-Planning_and_acting.ipynb
  docs/source/notebooks/Example_3_Multi_armed_bandit.ipynb
  docs/source/notebooks/Example_4_Causal_discovery.ipynb
  pyhgf/model/network.py
  pyhgf/utils/beliefs_propagation.py
  pyhgf/utils/sample_node_distribution.py
  tests/test_binary.py
  tests/test_utils.py
Labels: enhancement, models, networks

#288 fix links and proofs rendering in the documentation
  .github/workflows/docs.yml
  docs/source/conf.py
  docs/source/learn.md
  docs/source/notebooks/Example_4_Causal_discovery.ipynb
  poetry.lock
  pyproject.toml
Labels: documentation

#290 add generative sampling functionalities to the Network class
  docs/source/api.rst
  docs/source/notebooks/0.4-Planning_and_acting.ipynb
  docs/source/notebooks/Example_1_Heart_rate_variability.ipynb
  poetry.lock
  pyhgf/model/network.py
  pyhgf/plots/graphviz/__init__.py
  pyhgf/plots/matplotlib/__init__.py
  pyhgf/plots/matplotlib/plot_correlations.py
  pyhgf/plots/matplotlib/plot_nodes.py
  pyhgf/plots/matplotlib/plot_samples.py
  pyhgf/plots/matplotlib/plot_trajectories.py
  pyhgf/utils/__init__.py
  pyhgf/utils/sample.py
  pyproject.toml
  tests/test_plots.py
  tests/test_utils.py
Labels: enhancement, networks
