Repository ComputationalPsychiatry/pyhgf, pull requests merged in 2025-01, with the labels that each got.

#266 Add support for generalised Bayesian filtering with dynamic learning rate in JAX
  docs/source/api.rst
  docs/source/images/multivariate_hgf.gif
  docs/source/images/multivariate_normal.gif
  docs/source/notebooks/0.3-Generalised_filtering.ipynb
  pyhgf/math.py
  pyhgf/model/add_nodes.py
  pyhgf/updates/posterior/exponential.py
  pyhgf/updates/prediction/dirichlet.py
  pyhgf/updates/prediction_error/dirichlet.py
  pyhgf/updates/prediction_error/exponential.py
  pyhgf/utils/get_update_sequence.py
  tests/test_math.py
  tests/test_nodes/test_exponential_family.py
Labels: update functions, nodes, networks

#275 add a plot_network method using NetworkX as backende
  docs/source/api.rst
  poetry.lock
  pyhgf/model/network.py
  pyhgf/plots.py
  pyhgf/plots/__init__.py
  pyhgf/plots/graphviz/__init__.py
  pyhgf/plots/graphviz/plot_correlations.py
  pyhgf/plots/graphviz/plot_network.py
  pyhgf/plots/graphviz/plot_nodes.py
  pyhgf/plots/graphviz/plot_trajectories.py
  pyhgf/plots/networkx/__init__.py
  pyhgf/plots/networkx/plot_network.py
  pyhgf/updates/prediction_error/exponential.py
  pyproject.toml
  tests/test_plots.py
Labels: plotting

#249 Add update function and tutorial on causal prediction errors
  .gitignore
  docs/source/images/causal_discovery.png
  docs/source/learn.md
  docs/source/notebooks/.DS_Store
  docs/source/notebooks/Example_4_Causal_discovery.ipynb
Labels: documentation, nodes, networks
